import 'product.dart';

List<Product> productList = [
  Product(
    'iPhone 14 Pro Max',
    0,
    0,
    'assets/images/i14pm.png',
    'assets/images/i14pm_dt.png',
    false,
    false,
  ),
  Product(
    'iPhone 14 Pro',
    1,
    1,
    'assets/images/i14p.jpg',
    'assets/images/i14p_dt.png',
    false,
    false,
  ),
  Product(
    'iPhone 14 Plus',
    2,
    2,
    'assets/images/i14pl.png',
    'assets/images/i14pl_dt.png',
    false,
    false,
  ),
  Product(
    'iPhone 14',
    3,
    3,
    'assets/images/i14.jpg',
    'assets/images/i14_dt.png',
    false,
    false,
  ),
  Product(
    'iPhone 13 Mini',
    4,
    4,
    'assets/images/i13mini.png',
    'assets/images/i13mini_dt.png',
    false,
    false,
  ),
  Product(
    'iPhone 13',
    5,
    5,
    'assets/images/i13.jpg',
    'assets/images/i13_dt.png',
    false,
    false,
  ),
  Product(
    'iPhone 12',
    6,
    6,
    'assets/images/i12.png',
    'assets/images/i12_dt.png',
    false,
    false,
  ),
  Product(
    'iPhone SE 2020',
    7,
    7,
    'assets/images/ise.png',
    'assets/images/ise_dt.png',
    false,
    false,
  ),
];
